# ----------------------------- components -----------------------------

[sophon_tools_components_title]
en = "Game downloader"
ru = "Загрузчик игры"

[sophon_tools_cache_title]
en = "Downloader cache"
ru = "Кеш загрузчика"

[sophon_tools_cache_description]
en = "Disable the checkbox and press 'Apply changes' button to clear the downloader cache"
ru = "Выключите переключатель и нажмите на кнопку 'Применить изменения' для очистки кеша загрузчика"

[sophon_tools_cache_size_title]
en = "Cache size"
ru = "Размер кеша"

# ----------------------------- settings -----------------------------

[sophon_tools_settings_title]
en = "Game downloader"
ru = "Загрузчик игры"

[sophon_tools_settings_user_agent_title]
en = "User agent"
ru = "Браузер (user-agent)"

[sophon_tools_settings_user_agent_description]
en = "User agent string to use for API requests and files downloads"
ru = "Строка браузера (user agent), которая будет использована для запросов к API и скачивания файлов"

[sophon_tools_settings_proxy_title]
en = "Proxy"
ru = "Прокси"

[sophon_tools_settings_proxy_description]
en = "Proxy string to use for API requests and files downloads"
ru = "Прокси, который будет использован для запросов к API и скачивания файлов"

[sophon_tools_settings_threads_title]
en = "Runtime threads"
ru = "Количество потоков"

[sophon_tools_settings_threads_description]
en = "Amount of threads to use in the tokio async runtime. Keep 0 to use default value."
ru = "Количество потоков, которые будут использованы асинхронным планировщиком задач tokio. При 0 будет использовано значение по умолчанию."

[sophon_tools_settings_target_memory_usage_title]
en = "Target memory usage"
ru = "Использование системной памяти"

[sophon_tools_settings_target_memory_usage_description]
en = "Minimal amount of system memory in mebibytes available to downloader. Higher value will allow downloading more files in parallel."
ru = "Минимальное количество системной памяти в мебибайтах, доступное загрузчику. Большее значение позволит скачивать больше файлов одновременно."

[sophon_tools_settings_fast_verify_title]
en = "Fast verify"
ru = "Быстрая проверка"

[sophon_tools_settings_fast_verify_description]
en = "Use files sizes for verifications instead of calculating md5 hashes"
ru = "Использовать размеры файлов для проверок вместо вычислений md5 хешей"

# ----------------------------- pipeline -----------------------------

[download_sophon_tools_title]
en = "Download sophon-tools"
ru = "Загрузить sophon-tools"

[sophon_tools_game_update_not_supported]
en = "Game integration does not support game updating yet"
ru = "Обновление игры пока что не поддерживается"

[fetch_download_info_title]
en = "Fetch download info"
ru = "Запрос информации о загрузке"

[verify_available_files_title]
en = "Verify available files"
ru = "Проверка доступных файлов"

[download_new_files_title]
en = "Download new files"
ru = "Загрузка новых файлов"

[finalize_download_title]
en = "Finalize game download"
ru = "Завершение загрузки игры"
